export const dataSources = [
  {
    name: 'USDA FoodKeeper',
    url: 'https://www.foodsafety.gov/keep-food-safe/foodkeeper-app',
    use: 'Storage-window guidance for fridge, freezer, pantry, and counter items.',
  },
  {
    name: 'USDA FoodData Central',
    url: 'https://fdc.nal.usda.gov/',
    use: 'Common ingredient names and food categories.',
  },
  {
    name: 'USDA ERS Food Prices and Spending',
    url: 'https://www.ers.usda.gov/data-products/food-price-outlook/',
    use: 'Price realism for estimated saved-value ranges.',
  },
];

export const pantryCatalog = [
  {
    name: 'baby spinach',
    category: 'Produce',
    unit: 'bag',
    location: 'Fridge',
    storageDays: 5,
    value: 3.49,
    uses: ['egg scramble', 'grain bowl', 'green smoothie'],
  },
  {
    name: 'large eggs',
    category: 'Dairy',
    unit: 'carton',
    location: 'Fridge',
    storageDays: 28,
    value: 4.29,
    uses: ['fried rice', 'breakfast bowl', 'frittata'],
  },
  {
    name: 'whole milk',
    category: 'Dairy',
    unit: 'half gallon',
    location: 'Fridge',
    storageDays: 7,
    value: 3.19,
    uses: ['oatmeal', 'soup', 'smoothie'],
  },
  {
    name: 'cooked jasmine rice',
    category: 'Grains',
    unit: 'container',
    location: 'Fridge',
    storageDays: 4,
    value: 1.5,
    uses: ['fried rice', 'rice bowl', 'soup side'],
  },
  {
    name: 'dry pasta',
    category: 'Grains',
    unit: 'box',
    location: 'Pantry',
    storageDays: 365,
    value: 1.99,
    uses: ['tomato pasta', 'pantry bake', 'cold pasta salad'],
  },
  {
    name: 'chicken thighs',
    category: 'Protein',
    unit: 'lb',
    location: 'Freezer',
    storageDays: 120,
    value: 5.99,
    uses: ['tray bake', 'rice bowl', 'soup'],
  },
  {
    name: 'salmon fillet',
    category: 'Protein',
    unit: 'lb',
    location: 'Freezer',
    storageDays: 90,
    value: 9.99,
    uses: ['sheet pan dinner', 'rice bowl', 'salad protein'],
  },
  {
    name: 'firm tofu',
    category: 'Protein',
    unit: 'block',
    location: 'Fridge',
    storageDays: 7,
    value: 2.49,
    uses: ['lettuce wraps', 'stir fry', 'curry'],
  },
  {
    name: 'greek yogurt',
    category: 'Dairy',
    unit: 'tub',
    location: 'Fridge',
    storageDays: 10,
    value: 5.49,
    uses: ['sauce', 'breakfast bowl', 'marinade'],
  },
  {
    name: 'cheddar cheese',
    category: 'Dairy',
    unit: 'block',
    location: 'Fridge',
    storageDays: 21,
    value: 4.79,
    uses: ['soup', 'melt', 'egg bake'],
  },
  {
    name: 'romaine lettuce',
    category: 'Produce',
    unit: 'head',
    location: 'Fridge',
    storageDays: 7,
    value: 2.99,
    uses: ['wraps', 'salad', 'sandwich'],
  },
  {
    name: 'broccoli crowns',
    category: 'Produce',
    unit: 'head',
    location: 'Fridge',
    storageDays: 5,
    value: 2.59,
    uses: ['cheddar soup', 'stir fry', 'pasta'],
  },
  {
    name: 'white mushrooms',
    category: 'Produce',
    unit: 'box',
    location: 'Fridge',
    storageDays: 5,
    value: 3.29,
    uses: ['lentil stew', 'omelet', 'pasta'],
  },
  {
    name: 'carrots',
    category: 'Produce',
    unit: 'bag',
    location: 'Fridge',
    storageDays: 21,
    value: 2.49,
    uses: ['curry', 'soup', 'snack box'],
  },
  {
    name: 'bell peppers',
    category: 'Produce',
    unit: 'pcs',
    location: 'Fridge',
    storageDays: 7,
    value: 1.29,
    uses: ['tray bake', 'stir fry', 'fajitas'],
  },
  {
    name: 'zucchini',
    category: 'Produce',
    unit: 'pcs',
    location: 'Fridge',
    storageDays: 5,
    value: 1.1,
    uses: ['scramble', 'pasta', 'grain bowl'],
  },
  {
    name: 'cilantro',
    category: 'Produce',
    unit: 'bunch',
    location: 'Fridge',
    storageDays: 4,
    value: 1.49,
    uses: ['yogurt sauce', 'rice bowl', 'tacos'],
  },
  {
    name: 'cucumber',
    category: 'Produce',
    unit: 'pcs',
    location: 'Fridge',
    storageDays: 7,
    value: 0.99,
    uses: ['toast', 'salad', 'yogurt bowl'],
  },
  {
    name: 'tomatoes',
    category: 'Produce',
    unit: 'pcs',
    location: 'Counter',
    storageDays: 5,
    value: 1.79,
    uses: ['pasta', 'skillet', 'toast'],
  },
  {
    name: 'bananas',
    category: 'Produce',
    unit: 'bunch',
    location: 'Counter',
    storageDays: 5,
    value: 1.59,
    uses: ['smoothie', 'oatmeal', 'banana bread'],
  },
  {
    name: 'apples',
    category: 'Produce',
    unit: 'pcs',
    location: 'Counter',
    storageDays: 10,
    value: 1.25,
    uses: ['snack box', 'oatmeal', 'salad'],
  },
  {
    name: 'lemons',
    category: 'Produce',
    unit: 'pcs',
    location: 'Counter',
    storageDays: 14,
    value: 0.79,
    uses: ['dressing', 'marinade', 'tea'],
  },
  {
    name: 'yellow onions',
    category: 'Produce',
    unit: 'pcs',
    location: 'Pantry',
    storageDays: 30,
    value: 0.89,
    uses: ['soup base', 'stew', 'tray bake'],
  },
  {
    name: 'russet potatoes',
    category: 'Produce',
    unit: 'bag',
    location: 'Pantry',
    storageDays: 30,
    value: 4.49,
    uses: ['salmon plate', 'soup', 'hash'],
  },
  {
    name: 'sourdough bread',
    category: 'Bakery',
    unit: 'loaf',
    location: 'Counter',
    storageDays: 4,
    value: 5.99,
    uses: ['toast', 'melt', 'croutons'],
  },
  {
    name: 'turkey slices',
    category: 'Protein',
    unit: 'pack',
    location: 'Fridge',
    storageDays: 5,
    value: 6.49,
    uses: ['sandwich', 'melt', 'snack plate'],
  },
  {
    name: 'black beans',
    category: 'Canned',
    unit: 'can',
    location: 'Pantry',
    storageDays: 540,
    value: 1.29,
    uses: ['skillet', 'rice bowl', 'soup'],
  },
  {
    name: 'coconut milk',
    category: 'Canned',
    unit: 'can',
    location: 'Pantry',
    storageDays: 540,
    value: 2.19,
    uses: ['curry', 'soup', 'oats'],
  },
  {
    name: 'rolled oats',
    category: 'Grains',
    unit: 'container',
    location: 'Pantry',
    storageDays: 365,
    value: 4.99,
    uses: ['breakfast bowl', 'smoothie', 'bake'],
  },
  {
    name: 'red lentils',
    category: 'Grains',
    unit: 'bag',
    location: 'Pantry',
    storageDays: 365,
    value: 3.49,
    uses: ['stew', 'curry', 'soup'],
  },
  {
    name: 'peanut butter',
    category: 'Condiments',
    unit: 'jar',
    location: 'Pantry',
    storageDays: 180,
    value: 3.99,
    uses: ['oats', 'toast', 'sauce'],
  },
  {
    name: 'soy sauce',
    category: 'Condiments',
    unit: 'bottle',
    location: 'Pantry',
    storageDays: 365,
    value: 3.79,
    uses: ['stir fry', 'marinade', 'fried rice'],
  },
  {
    name: 'frozen peas',
    category: 'Frozen',
    unit: 'bag',
    location: 'Freezer',
    storageDays: 240,
    value: 2.29,
    uses: ['fried rice', 'soup', 'pasta'],
  },
  {
    name: 'frozen berries',
    category: 'Frozen',
    unit: 'bag',
    location: 'Freezer',
    storageDays: 240,
    value: 4.99,
    uses: ['smoothie', 'oatmeal', 'yogurt bowl'],
  },
  {
    name: 'ground cumin',
    category: 'Spices',
    unit: 'jar',
    location: 'Pantry',
    storageDays: 730,
    value: 3.49,
    uses: ['black beans', 'curry', 'stew'],
  },
];

export const recipeTemplates = [
  {
    title: 'Spinach egg rice bowl',
    ingredients: ['baby spinach', 'large eggs', 'cooked jasmine rice', 'soy sauce'],
    tags: ['quick', 'use-soon', 'breakfast-for-dinner'],
    cookTimeMinutes: 18,
    difficulty: 'Easy',
  },
  {
    title: 'Tomato yogurt pasta',
    ingredients: ['dry pasta', 'tomatoes', 'greek yogurt', 'baby spinach'],
    tags: ['vegetarian', 'creamy', 'weeknight'],
    cookTimeMinutes: 25,
    difficulty: 'Easy',
  },
  {
    title: 'Crispy tofu lettuce wraps',
    ingredients: ['firm tofu', 'romaine lettuce', 'cucumber', 'soy sauce', 'cilantro'],
    tags: ['vegetarian', 'high protein', 'fresh'],
    cookTimeMinutes: 30,
    difficulty: 'Medium',
  },
  {
    title: 'Chicken pepper tray bake',
    ingredients: ['chicken thighs', 'bell peppers', 'yellow onions', 'lemons'],
    tags: ['sheet pan', 'protein', 'prep'],
    cookTimeMinutes: 45,
    difficulty: 'Medium',
  },
  {
    title: 'Broccoli cheddar soup',
    ingredients: ['broccoli crowns', 'cheddar cheese', 'whole milk', 'yellow onions'],
    tags: ['comfort', 'use-soon', 'soup'],
    cookTimeMinutes: 35,
    difficulty: 'Medium',
  },
  {
    title: 'Mushroom lentil stew',
    ingredients: ['white mushrooms', 'red lentils', 'carrots', 'yellow onions', 'ground cumin'],
    tags: ['vegetarian', 'freezer-friendly', 'budget'],
    cookTimeMinutes: 40,
    difficulty: 'Medium',
  },
  {
    title: 'Salmon potato plate',
    ingredients: ['salmon fillet', 'russet potatoes', 'lemons', 'baby spinach'],
    tags: ['high protein', 'weekend', 'balanced'],
    cookTimeMinutes: 35,
    difficulty: 'Weekend',
  },
  {
    title: 'Black bean tomato skillet',
    ingredients: [
      'black beans',
      'tomatoes',
      'yellow onions',
      'ground cumin',
      'cooked jasmine rice',
    ],
    tags: ['pantry', 'budget', 'one-pan'],
    cookTimeMinutes: 25,
    difficulty: 'Easy',
  },
  {
    title: 'Cucumber cilantro yogurt toast',
    ingredients: ['sourdough bread', 'greek yogurt', 'cucumber', 'cilantro', 'lemons'],
    tags: ['fresh', 'snack', 'no-waste'],
    cookTimeMinutes: 10,
    difficulty: 'Easy',
  },
  {
    title: 'Carrot coconut curry',
    ingredients: ['carrots', 'coconut milk', 'red lentils', 'ground cumin', 'cooked jasmine rice'],
    tags: ['vegetarian', 'pantry', 'comfort'],
    cookTimeMinutes: 35,
    difficulty: 'Medium',
  },
  {
    title: 'Turkey sourdough melt',
    ingredients: ['turkey slices', 'sourdough bread', 'cheddar cheese', 'tomatoes'],
    tags: ['quick', 'lunch', 'use-soon'],
    cookTimeMinutes: 14,
    difficulty: 'Easy',
  },
  {
    title: 'Zucchini egg scramble',
    ingredients: ['zucchini', 'large eggs', 'cheddar cheese', 'baby spinach'],
    tags: ['breakfast', 'quick', 'use-soon'],
    cookTimeMinutes: 16,
    difficulty: 'Easy',
  },
  {
    title: 'Berry peanut oatmeal',
    ingredients: ['rolled oats', 'frozen berries', 'peanut butter', 'whole milk'],
    tags: ['breakfast', 'pantry', 'batch'],
    cookTimeMinutes: 12,
    difficulty: 'Easy',
  },
  {
    title: 'Pea and mushroom pantry pasta',
    ingredients: ['dry pasta', 'frozen peas', 'white mushrooms', 'cheddar cheese'],
    tags: ['pantry', 'vegetarian', 'low-waste'],
    cookTimeMinutes: 24,
    difficulty: 'Easy',
  },
];
